version: '3.8'

services:
  olympo-db:
    image: postgres:15-alpine
    container_name: olympo_postgres_local
    environment:
      POSTGRES_USER: olympo_user
      POSTGRES_PASSWORD: olympo_password
      POSTGRES_DB: olympo_management
    ports:
      - "5432:5432"
    volumes:
      - olympo_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  olympo_db_data: