version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: olympo_postgres
    restart: always
    environment:
      POSTGRES_USER: olympo_admin
      POSTGRES_PASSWORD: olympo_password
      POSTGRES_DB: olympo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: